{% set name = "jupyter-hdfscm" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c719ea23e4d2a9d516b1cd1516e39905c61935aa205b88366d0aeb80ed7caac6

build:
  number: 3
  skip: True  # [win or osx or py<35]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - notebook >=4.0
    - pyarrow >=0.9.0

test:
  imports:
    - hdfscm

about:
  home: https://github.com/jcrist/hdfscm
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Jupyter ContentsManager for HDFS
  description: |
    A Jupyter ContentsManager for HDFS. Allows storing notebooks and other
    files on HDFS.
  doc_url: https://jcrist.github.io/hdfscm/
  dev_url: https://github.com/jcrist/hdfscm

extra:
  recipe-maintainers:
    - jcrist
