travis:
  secure:
    BINSTAR_TOKEN: FVG3ImLmEntibJ5WjspV3WXckdOLDNufg8RfsrPt6SGMi5mnX6v1nfZ02TqOt4zmNxLjOAopunIhMDo9UCkG7VAGNhM3rpocqCzkSSubb597dp9Eds/lU9QsSGDUfIT71DwPDrbmsHoeGr+vSKMNzEhTn3LTRL9Jgas0VgL3Ye2X86o/yanhVvOWj+b+AzTnjwmuZaVLQnrTXYD40dlVxbYwg2dVnw4k1VKg76Mc+YsNeFpJaEGwu7BVAxS95ejqX+rgLgHnldRcZE18rFQqBxdJHmftUGtvm/tzYPLwRj2Ca9it/zE//7tcBOgELpTzlttbOSIwK2wTkjwVa+pHpVvr+v8s1RJXI2bzuPfTM5UC8IXGqi2o8jUuUYeFCcPqMM2m99iWvlFZH75tcpspKEMTzpvsGK2IdnZlPxJyd9Fz/4sXeq3qnh2O2sSROvoMqQ/wFrvsbpKWW+8y6udT3newpPcyA8qDdYJSYYyU2PlnU/pA4m2kNApC7Ct0Ar20tvfYyyb2cthRLT+B5/GOgflsYUNlD7w+4zQctFzxxe/3B8vueijY0/TG6erE9eTU57rtOKTd+wgpZ0ZaI0xZJnHwDvMY4wHkKCa+7zBG+8QZFQXJ2ji1p53XFlxeS/XqnI1od/HqcRkNFSS9MB9Cuo1hsHu9asZvTE8Yv0vXCVU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
