appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RO2VLZf2oiqm6FHjnYjEoOR2Imgoa9uwKX845GFe1rbMXW70gc+H/cym/ajFAnTGJ2PKLzKTXkbwGw389O6HNlsWEHNxKwbMCTFtB30UF/Tk0nLJaFpkIYrzPRz6TWylfo9bGe/JV7vwH5Pm1bXteNwciBa5asxOKX+C2OkHXYvqEYoCKG2ONBpDP4gh42PV2S4EurMpPebFLbBGxVhxDv1Up5IG1wDySjj3qBSqSN5+FmOIY6aVKqAaEgn0kePoSidxHAPkJPgIYuGXIK1n7tk6EMyI0bRHyl2lYElD08gkd3B1q37jc2zBuSDl3RdIm2i140B0myaiXsDuUhRtz4wtnUhcvYW43jiEE+HZNrbjTVaY2FsiCFe5Z8nF6PR+6dPlSEv7ftekbkmD4Tx+P8KcYx0S1rp9t+x2WjHnCRbm1Qr83I54BKEdOOM8kK7EC+X5gbK7EvnXPWBCI5iNoJBLv66zwLeG1DFFqGFHDHJgiMuo/oWpLXFie87ciwbJJ+PBK1nJNN/Kp/ZWtZspmgEbzEKP8Tp3zNOLaz9Pnc7oO44d3vlZUdek1zhSa5VZp2ls4w4D/fnVErrldtTfylVxIGAY+R1YvbH1yLl1LPhkcVjVvO2c6EqyZ57YiExV8OlFh7glmpHAhAeDutuQvovV9bkThPSvrZ4xNKnZx7o=}
